import { useEffect, useMemo, useState } from "react";
import { LoaderCircle, Plus, Search, ShieldCheck, UserRound, X } from "lucide-react";
import type { Tables } from "../../lib/supabase/database.types";
import { getFestivalMembers } from "../../lib/supabase/services";
import { supabase } from "../../lib/supabase/client";
import { useAuth } from "../auth/auth-context";

type Member = Tables<"festival_members"> & { profile: Pick<Tables<"profiles">, "display_name" | "student_number"> | null };
type Role = "admin" | "staff" | "booth_operator";
const labels: Record<Role | "participant" | "owner", string> = { participant: "참가자", admin: "관리자", staff: "스태프", booth_operator: "부스 운영자", owner: "축제 책임자" };
const extra: Role[] = ["admin", "staff", "booth_operator"];

export function AdminPermissionsPage() {
  const { activeMembership, user } = useAuth(); const festivalId = activeMembership?.festival_id;
  const [members, setMembers] = useState<Member[]>([]); const [roles, setRoles] = useState<Record<string, string[]>>({}); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState("");
  const load = async () => { if (!festivalId || !supabase) return; const [memberRows, roleRows] = await Promise.all([getFestivalMembers(festivalId), supabase.from("festival_member_roles").select("user_id, role").eq("festival_id", festivalId)]); if (roleRows.error) throw roleRows.error; setMembers(memberRows); setRoles((roleRows.data ?? []).reduce<Record<string, string[]>>((all, item) => { (all[item.user_id] ??= []).push(item.role); return all; }, {})); };
  useEffect(() => { if (!festivalId || !supabase) return; void Promise.all([getFestivalMembers(festivalId), supabase.from("festival_member_roles").select("user_id, role").eq("festival_id", festivalId)]).then(([memberRows, roleRows]) => { if (roleRows.error) throw roleRows.error; setMembers(memberRows); setRoles((roleRows.data ?? []).reduce<Record<string, string[]>>((all, item) => { (all[item.user_id] ??= []).push(item.role); return all; }, {})); }).catch((caught) => setError(caught instanceof Error ? caught.message : "사용자 목록을 불러오지 못했습니다.")).finally(() => setLoading(false)); }, [festivalId]);
  const shown = useMemo(() => members.filter((member) => `${member.profile?.display_name ?? ""} ${member.profile?.student_number ?? ""}`.toLowerCase().includes(query.toLowerCase())), [members, query]);
  const change = async (memberId: string, role: Role, add: boolean) => { if (!supabase || !festivalId) return; setSaving(memberId); setError(""); const { error: mutationError } = add ? await supabase.from("festival_member_roles").insert({ festival_id: festivalId, user_id: memberId, role }) : await supabase.from("festival_member_roles").delete().eq("festival_id", festivalId).eq("user_id", memberId).eq("role", role); if (mutationError) setError(mutationError.message); else await load(); setSaving(null); };
  return <main className="management-page"><header className="management-header"><div><span>ACCESS CONTROL</span><h1>사용자 권한</h1><p>학생은 기본 참가자입니다. 필요한 운영 권한을 추가하고, 더 이상 필요 없으면 제거하세요.</p></div></header><label className="catalog-search management-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름 또는 학번 검색" /></label>{error && <p className="form-error">{error}</p>}<section className="permission-table permission-chips">{loading ? <div className="management-loading"><LoaderCircle /> 불러오는 중…</div> : shown.map((member) => { const current = roles[member.user_id] ?? []; const canAdd = extra.filter((role) => !current.includes(role)); return <article key={member.user_id}><span className="member-avatar">{member.profile?.display_name?.slice(0, 1) ?? <UserRound />}</span><span className="member-info"><b>{member.profile?.display_name ?? "이름 미설정"}</b><small>{member.profile?.student_number ?? "교직원"} · {member.user_id === user?.id ? "나" : "가입자"}</small></span><span className="role-chip-list"><span className="role-chip fixed"><ShieldCheck /> {labels.participant}</span>{current.filter((role) => role === "owner" || extra.includes(role as Role)).map((role) => role === "owner" ? <span className="role-chip fixed" key={role}><ShieldCheck /> {labels.owner}</span> : <button className="role-chip" disabled={saving === member.user_id} key={role} onClick={() => void change(member.user_id, role as Role, false)}>{labels[role as Role]} <X /></button>)}{canAdd.length > 0 && <label className="add-role"><Plus /><select value="" disabled={saving === member.user_id} onChange={(event) => { if (event.target.value) void change(member.user_id, event.target.value as Role, true); }}><option value="">권한 추가</option>{canAdd.map((role) => <option key={role} value={role}>{labels[role]}</option>)}</select></label>}</span></article>; })}{!loading && !shown.length && <div className="management-empty"><UserRound /><h2>일치하는 사용자가 없어요.</h2></div>}</section></main>;
}
