import { useEffect, useMemo, useState } from "react";
import { LoaderCircle, Plus, Search, ShieldCheck, UserRound, X } from "lucide-react";
import type { Tables } from "../../lib/supabase/database.types";
import { getFestivalMembers } from "../../lib/supabase/services";
import { supabase } from "../../lib/supabase/client";
import { useAuth } from "../auth/auth-context";

type Member = Tables<"festival_members"> & { profile: Pick<Tables<"profiles">, "display_name" | "student_number"> | null };
type Role = "admin" | "staff" | "booth_operator";
const labels: Record<Role | "participant" | "owner", string> = { participant: "참가자", admin: "관리자", staff: "스태프", booth_operator: "부스 운영자", owner: "축제 책임자" };
const extra: Role[] = ["admin", "staff", "booth_operator"];
const STAFF_NUMBERS = ["9999", "9998"];
function baseLabel(studentNumber: string | null | undefined) {
  if (studentNumber === "9999") return labels.admin;
  if (studentNumber === "9998") return labels.booth_operator;
  return labels.participant;
}

export function AdminPermissionsPage() {
  const { activeMembership, user } = useAuth(); const festivalId = activeMembership?.festival_id;
  const [members, setMembers] = useState<Member[]>([]); const [roles, setRoles] = useState<Record<string, string[]>>({}); const [booths, setBooths] = useState<Tables<"booths">[]>([]); const [assignments, setAssignments] = useState<Record<string, number[]>>({}); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [error, setError] = useState("");
  const load = async () => { if (!festivalId || !supabase) return; const [memberRows, roleRows, boothRows, assignmentRows] = await Promise.all([getFestivalMembers(festivalId), supabase.from("festival_member_roles").select("user_id, role").eq("festival_id", festivalId), supabase.from("booths").select("*").eq("festival_id", festivalId).order("name"), supabase.from("booth_members").select("user_id, booth_id")]); if (roleRows.error || boothRows.error || assignmentRows.error) throw roleRows.error ?? boothRows.error ?? assignmentRows.error; setMembers(memberRows); setBooths(boothRows.data ?? []); setRoles((roleRows.data ?? []).reduce<Record<string, string[]>>((all, item) => { (all[item.user_id] ??= []).push(item.role); return all; }, {})); setAssignments((assignmentRows.data ?? []).reduce<Record<string, number[]>>((all, item) => { (all[item.user_id] ??= []).push(item.booth_id); return all; }, {})); };
  useEffect(() => { if (!festivalId || !supabase) return; void Promise.all([getFestivalMembers(festivalId), supabase.from("festival_member_roles").select("user_id, role").eq("festival_id", festivalId), supabase.from("booths").select("*").eq("festival_id", festivalId).order("name"), supabase.from("booth_members").select("user_id, booth_id")]).then(([memberRows, roleRows, boothRows, assignmentRows]) => { if (roleRows.error || boothRows.error || assignmentRows.error) throw roleRows.error ?? boothRows.error ?? assignmentRows.error; setMembers(memberRows); setBooths(boothRows.data ?? []); setRoles((roleRows.data ?? []).reduce<Record<string, string[]>>((all, item) => { (all[item.user_id] ??= []).push(item.role); return all; }, {})); setAssignments((assignmentRows.data ?? []).reduce<Record<string, number[]>>((all, item) => { (all[item.user_id] ??= []).push(item.booth_id); return all; }, {})); }).catch((caught) => setError(caught instanceof Error ? caught.message : "사용자 목록을 불러오지 못했습니다.")).finally(() => setLoading(false)); }, [festivalId]);
  const staffPool = useMemo(() => members.filter((member) => STAFF_NUMBERS.includes(member.profile?.student_number ?? "")), [members]);
  const shown = useMemo(() => staffPool.filter((member) => `${member.profile?.display_name ?? ""} ${member.profile?.student_number ?? ""}`.toLowerCase().includes(query.toLowerCase())), [staffPool, query]);
  const change = async (memberId: string, role: Role, add: boolean) => { if (!supabase || !festivalId) return; setSaving(memberId); setError(""); if (!add && role === "booth_operator") await supabase.from("booth_members").delete().eq("user_id", memberId); const { error: mutationError } = add ? await supabase.from("festival_member_roles").insert({ festival_id: festivalId, user_id: memberId, role }) : await supabase.from("festival_member_roles").delete().eq("festival_id", festivalId).eq("user_id", memberId).eq("role", role); if (mutationError) setError(mutationError.message); else await load(); setSaving(null); };
  const assignBooth = async (memberId: string, boothId: number) => { if (!supabase || !festivalId) return; setSaving(memberId); setError(""); const { error: roleError } = await supabase.from("festival_member_roles").insert({ festival_id: festivalId, user_id: memberId, role: "booth_operator" }); if (roleError && roleError.code !== "23505") { setError(roleError.message); setSaving(null); return; } const { error: assignmentError } = await supabase.from("booth_members").insert({ booth_id: boothId, user_id: memberId, role: "operator" }); if (assignmentError) setError(assignmentError.message); else await load(); setSaving(null); };
  const removeBooth = async (memberId: string, boothId: number) => { if (!supabase) return; setSaving(memberId); const { error: removalError } = await supabase.from("booth_members").delete().eq("user_id", memberId).eq("booth_id", boothId); if (removalError) setError(removalError.message); else await load(); setSaving(null); };
  return <main className="management-page"><header className="management-header"><div><span>ACCESS CONTROL</span><h1>사용자 권한</h1><p>학번 9999(관리자)·9998(부스 운영자)로 가입한 계정에만 추가 권한을 부여할 수 있습니다. 일반 참가자는 이 목록에 나타나지 않습니다.</p></div></header><label className="catalog-search management-search"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름 또는 학번 검색" /></label>{error && <p className="form-error">{error}</p>}<section className="permission-table permission-chips">{loading ? <div className="management-loading"><LoaderCircle /> 불러오는 중…</div> : shown.map((member) => { const current = roles[member.user_id] ?? []; const canAdd = extra.filter((role) => role !== "booth_operator" && !current.includes(role)); const assigned = assignments[member.user_id] ?? []; const selectable = booths.filter((booth) => !assigned.includes(booth.id)); return <article key={member.user_id}><span className="member-avatar">{member.profile?.display_name?.slice(0, 1) ?? <UserRound />}</span><span className="member-info"><b>{member.profile?.display_name ?? "이름 미설정"}</b><small>{member.profile?.student_number ?? "교직원"} · {member.user_id === user?.id ? "나" : "가입자"}</small></span><span className="role-chip-list"><span className="role-chip fixed"><ShieldCheck /> {baseLabel(member.profile?.student_number)}</span>{current.filter((role) => role === "owner" || extra.includes(role as Role)).map((role) => role === "owner" ? <span className="role-chip fixed" key={role}><ShieldCheck /> {labels.owner}</span> : <button className="role-chip" disabled={saving === member.user_id} key={role} onClick={() => void change(member.user_id, role as Role, false)}>{labels[role as Role]} <X /></button>)}{assigned.map((boothId) => <button className="role-chip booth-assignment" disabled={saving === member.user_id} key={boothId} onClick={() => void removeBooth(member.user_id, boothId)}>담당: {booths.find((booth) => booth.id === boothId)?.name ?? "부스"} <X /></button>)}{selectable.length > 0 && <label className="add-role"><Plus /><select value="" disabled={saving === member.user_id} onChange={(event) => { if (event.target.value) void assignBooth(member.user_id, Number(event.target.value)); }}><option value="">담당 부스 추가</option>{selectable.map((booth) => <option key={booth.id} value={booth.id}>{booth.name}</option>)}</select></label>}{canAdd.length > 0 && <label className="add-role"><Plus /><select value="" disabled={saving === member.user_id} onChange={(event) => { if (event.target.value) void change(member.user_id, event.target.value as Role, true); }}><option value="">권한 추가</option>{canAdd.map((role) => <option key={role} value={role}>{labels[role]}</option>)}</select></label>}</span></article>; })}{!loading && !shown.length && <div className="management-empty"><UserRound /><h2>일치하는 사용자가 없어요.</h2></div>}</section></main>;
}
