import { useEffect, useState, type FormEvent } from "react";
import { Save, Store } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import type { Tables } from "../../lib/supabase/database.types";
import { supabase } from "../../lib/supabase/client";
import { updateBooth } from "../../lib/supabase/services";
import { useAuth } from "../auth/auth-context";

export function BoothSettingsPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [booth, setBooth] = useState<Tables<"booths"> | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: "", short_description: "", description: "", location: "", accent_color: "#f52a9a", status: "draft", estimated_wait_minutes: 0 });
  useEffect(() => { if (!supabase || !user) return; void supabase.from("booth_members").select("booth_id, booths(*)").eq("user_id", user.id).limit(1).maybeSingle().then(({ data, error: loadError }) => { if (loadError || !data?.booths) { setError(loadError?.message ?? "담당 부스를 찾을 수 없습니다."); return; } const item = data.booths as unknown as Tables<"booths">; setBooth(item); setForm({ name: item.name, short_description: item.short_description ?? "", description: item.description ?? "", location: item.location ?? "", accent_color: item.accent_color, status: item.status, estimated_wait_minutes: item.estimated_wait_minutes }); }); }, [user]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!booth) return; setSaving(true); setError(""); try { await updateBooth(booth.id, { ...form, short_description: form.short_description || null, description: form.description || null, location: form.location || null }); navigate("/booth"); } catch (caught) { setError(caught instanceof Error ? caught.message : "부스 정보를 저장하지 못했습니다."); } finally { setSaving(false); } };
  return <main className="management-page"><header className="management-header"><div><Link className="back-link" to="/booth">부스 운영</Link><span>BOOTH SETTINGS</span><h1>부스 꾸미기</h1><p>학생에게 보이는 소개와 현장 운영 상태를 직접 관리합니다.</p></div></header><form className="editor-form" onSubmit={submit}>{error && <p className="form-error">{error}</p>}<label><span>부스 이름</span><input required maxLength={80} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label><span>한 줄 소개</span><input maxLength={160} value={form.short_description} onChange={(e) => setForm({ ...form, short_description: e.target.value })} placeholder="예: 친구들과 사진을 남기는 포토 부스" /></label><label><span>상세 안내</span><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label><span>위치</span><input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="예: 운동장 중앙" /></label><label><span>운영 상태</span><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="open">운영 중</option><option value="paused">잠시 멈춤</option><option value="closed">운영 종료</option><option value="draft">비공개</option></select></label><label><span>예상 대기 시간 (분)</span><input type="number" min="0" max="600" value={form.estimated_wait_minutes} onChange={(e) => setForm({ ...form, estimated_wait_minutes: Number(e.target.value) })} /></label><label><span>대표 색상</span><span className="color-choice"><input type="color" value={form.accent_color} onChange={(e) => setForm({ ...form, accent_color: e.target.value })} /><b>{form.accent_color}</b></span></label><footer><Link className="secondary-action" to="/booth">취소</Link><button className="primary-action" disabled={saving || !booth}><Save /> {saving ? "저장 중…" : "변경 저장"}</button></footer></form></main>;
}
